#!/bin/bash
# Whonix build menu script welcome
clear
echo "================================================================="
echo "================================================================="
echo "You have completed a network install of Debian 7.3 (wheezy) from a minimal CD"
echo "In order to save your progress take a snapshot of this Virtual Machine." 
echo "Click 'Machine' and 'Take Snaphost'. Name it 'First login'. 
echo "After that, type 'whonix-build' and press Enter to starting building Whonix"
echo "================================================================="
echo "================================================================="
