#!/bin/bash
# Whonix build menu script welcome
echo "=========================================================="
echo "=========================================================="
echo "You have completed a network install of Debian Wheezy (stable) 7.3 from a minimal CD"
echo "In order to save your progress it's recommended to take a snapshot of this Virtual Machine." 
echo "Click 'Machine' and 'Take Snaphost'. Name it 'First login'. 
echo "After that, if you are ready to starting building Whonix, type 'whonix-build' and press Enter"
echo "=========================================================="
echo "=========================================================="
