#!/bin/bash
# Whonix build menu script
# It updates, upgrades and runs git clone and checkout

#sudo apt-get update && sudo apt-get dist-upgrade -y

# Install git 1.8.5 (new git-c function)
#sudo apt-get -t wheezy-backports install git -y

#condition=
#until [ "$condition" = "0" ]; do

#clear
echo "==============================================================================="
echo "Which version of Whonix would you like to build?"
echo ""
echo "Latest stable release (8, 02-2014)                     --> Press 1 "
echo "Developer or testers-only releases                     --> Press 2 "
echo "Exit the build menu                                    --> Press 0 "
echo ""
echo "Select by pressing the number and then ENTER"
echo "==============================================================================="
read answer1

case "$answer1" in 0 )
echo "Exiting the build menu ..."; 
sleep 2
clear
echo "If you wish to build Whonix again just type 'whonix' and press Enter"
exit
esac

case "$answer1" in 1 )
echo "Preparing the menu for Whonix stable ..."
sleep 1
if [ -d "/home/user/Whonix" ] 
  then
       sudo rm -r Whonix 
fi &&

git clone https://github.com/Whonix/Whonix && git -C "/home/user/Whonix" checkout 7.3.7

clear
echo "==============================================================================="
echo "What would you like to do?"
echo ""
echo "Build Whonix-Gateway virtual machine image            --> Press 1 "
echo "Build Whonix-Workstation virtual machine image        --> Press 2 "
echo "Build Whonix-Gateway on hardware                      --> Press 3 "
echo "Build Whonix-Gateway on a virtual machine             --> Press 4 "
echo "Exit the build menu                                   --> Press 0 "
echo ""
echo "Select by pressing the number and then ENTER"
echo "==============================================================================="
read answer2

case $answer2 in 1)
sudo ./Whonix/whonix_build --build --tor-gateway
esac

case $answer2 in 2)
sudo ./Whonix/whonix_build --build --tor-workstation
esac

case $answer2 in 3)
sudo ./Whonix/whonix_build --tor-gateway --bare-metal --build
esac

case $answer2 in 4)
sudo ./no command yet
esac

case $answer in 0)
echo "Exiting the build menu ..."; 
sleep 2
exit
esac
esac

case "$answer1" in 2 )

if [ -d "/home/user/nothing-to-see" ] 
  then
       sudo rm -r nothing-to-see 
fi &&

git clone https://github.com/adrelanos/nothing-to-see && git -C "/home/user/nothing-to-see" tag
echo "Type in which version do you want to build and press Enter"
esac
#read answer

#case "$answer1" in * )
#echo "You have pressed an invalid key, please try again."
#sleep 2
#sh /home/user/whonix-build
#esac

case "$answer1" in "answer" )
git -C "/home/user/nothing-to-see" checkout "$answer"

clear
echo "==============================================================================="
echo "What would you like to do?"
echo ""
echo "Build Whonix-Gateway virtual machine image            --> Press 1 "
echo "Build Whonix-Workstation virtual machine image        --> Press 2 "
echo "Build Whonix-Gateway on hardware                      --> Press 3 "
echo "Build Whonix-Gateway on a virtual machine             --> Press 4 "
echo "Exit the build menu                                   --> Press 0 "
echo ""
echo "Select by pressing the number and then ENTER"
echo "==============================================================================="
#read answer

#case $answer in 1)
#sudo ./Whonix/whonix_build --build --tor-gateway
#esac

#case $answer in 2)
#sudo ./Whonix/whonix_build --build --tor-workstation
#esac

#case $answer in 3)
#sudo ./Whonix/whonix_build --tor-gateway --bare-metal --build
#esac

#case $answer in 4)
#sudo ./no command yet
#esac

case $answer in 0)
echo "Exiting the build menu ..."; 
sleep 2
exit
esac
esac

#done
